// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_sample_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcSample.Contracts.Services {

  /// <summary>Holder for reflection information generated from grpc_sample_service.proto</summary>
  public static partial class GrpcSampleServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for grpc_sample_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GrpcSampleServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlncnBjX3NhbXBsZV9zZXJ2aWNlLnByb3RvEgpncnBjc2FtcGxlGiJncnBj",
            "X3NhbXBsZV9zZXJ2aWNlX21lc3NhZ2VzLnByb3RvGh5nb29nbGUvcHJvdG9i",
            "dWYvd3JhcHBlcnMucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAu",
            "cHJvdG8aG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90byKaAgoSSGVsbGVX",
            "b3JsZFJlc3BvbnNlEjEKDG51bGxhYmxlX2ludBgBIAEoCzIbLmdvb2dsZS5w",
            "cm90b2J1Zi5JbnQ2NFZhbHVlEjYKEmRhdGVfdGltZV9wcm9wZXJ0eRgDIAEo",
            "CzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDwoHbWVzc2FnZRgEIAEo",
            "CRI1Cglmb29fZmllbGQYBSABKA4yIi5ncnBjc2FtcGxlLkhlbGxlV29ybGRS",
            "ZXNwb25zZS5Gb28iNQoDRm9vEgsKB1VOS05PV04QABIPCgtGSVJTVF9WQUxV",
            "RRACEhAKDFNFQ09ORF9WQUxVRRADSgQIAhADSgQIDxAQSgQICRAMUgNmb29S",
            "A2JhcjKpAgoRR3JwY1NhbXBsZVNlcnZpY2USSQoNR2V0SGVsbG9Xb3JsZBIW",
            "Lmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoeLmdycGNzYW1wbGUuSGVsbGVXb3Js",
            "ZFJlc3BvbnNlIgASPQoIR2V0TGluZXMSGy5ncnBjc2FtcGxlLkdldExpbmVz",
            "UmVxdWVzdBoQLmdycGNzYW1wbGUuTGluZSIAMAESPQoDU3VtEhkuZ3JwY3Nh",
            "bXBsZS5OdW1iZXJNZXNzYWdlGhcuZ3JwY3NhbXBsZS5TdW1SZXNwb25zZSIA",
            "KAESSwoITXVsdGlwbHkSGy5ncnBjc2FtcGxlLk11bHRpcGx5UmVxdWVzdBoc",
            "LmdycGNzYW1wbGUuTXVsdGlwbHlSZXNwb25zZSIAKAEwAUIgqgIdR3JwY1Nh",
            "bXBsZS5Db250cmFjdHMuU2VydmljZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GrpcSample.Contracts.Messages.GrpcSampleServiceMessagesReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcSample.Contracts.Services.HelleWorldResponse), global::GrpcSample.Contracts.Services.HelleWorldResponse.Parser, new[]{ "NullableInt", "DateTimeProperty", "Message", "FooField" }, null, new[]{ typeof(global::GrpcSample.Contracts.Services.HelleWorldResponse.Types.Foo) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Hello World example message.
  ///
  ///CamelCase used for messages and rpc.
  /// </summary>
  public sealed partial class HelleWorldResponse : pb::IMessage<HelleWorldResponse> {
    private static readonly pb::MessageParser<HelleWorldResponse> _parser = new pb::MessageParser<HelleWorldResponse>(() => new HelleWorldResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HelleWorldResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcSample.Contracts.Services.GrpcSampleServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelleWorldResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelleWorldResponse(HelleWorldResponse other) : this() {
      NullableInt = other.NullableInt;
      DateTimeProperty = other.dateTimeProperty_ != null ? other.DateTimeProperty.Clone() : null;
      message_ = other.message_;
      fooField_ = other.fooField_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelleWorldResponse Clone() {
      return new HelleWorldResponse(this);
    }

    /// <summary>Field number for the "nullable_int" field.</summary>
    public const int NullableIntFieldNumber = 1;
    private static readonly pb::FieldCodec<long?> _single_nullableInt_codec = pb::FieldCodec.ForStructWrapper<long>(10);
    private long? nullableInt_;
    /// <summary>
    /// snake_case used form message properties.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long? NullableInt {
      get { return nullableInt_; }
      set {
        nullableInt_ = value;
      }
    }

    /// <summary>Field number for the "date_time_property" field.</summary>
    public const int DateTimePropertyFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dateTimeProperty_;
    /// <summary>
    /// xml comments will be autogenerated
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DateTimeProperty {
      get { return dateTimeProperty_; }
      set {
        dateTimeProperty_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 4;
    private string message_ = "";
    /// <summary>
    ///// ERROR!!!
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "foo_field" field.</summary>
    public const int FooFieldFieldNumber = 5;
    private global::GrpcSample.Contracts.Services.HelleWorldResponse.Types.Foo fooField_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GrpcSample.Contracts.Services.HelleWorldResponse.Types.Foo FooField {
      get { return fooField_; }
      set {
        fooField_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HelleWorldResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HelleWorldResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NullableInt != other.NullableInt) return false;
      if (!object.Equals(DateTimeProperty, other.DateTimeProperty)) return false;
      if (Message != other.Message) return false;
      if (FooField != other.FooField) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (nullableInt_ != null) hash ^= NullableInt.GetHashCode();
      if (dateTimeProperty_ != null) hash ^= DateTimeProperty.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (FooField != 0) hash ^= FooField.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (nullableInt_ != null) {
        _single_nullableInt_codec.WriteTagAndValue(output, NullableInt);
      }
      if (dateTimeProperty_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DateTimeProperty);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (FooField != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) FooField);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (nullableInt_ != null) {
        size += _single_nullableInt_codec.CalculateSizeWithTag(NullableInt);
      }
      if (dateTimeProperty_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DateTimeProperty);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (FooField != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FooField);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HelleWorldResponse other) {
      if (other == null) {
        return;
      }
      if (other.nullableInt_ != null) {
        if (nullableInt_ == null || other.NullableInt != 0L) {
          NullableInt = other.NullableInt;
        }
      }
      if (other.dateTimeProperty_ != null) {
        if (dateTimeProperty_ == null) {
          dateTimeProperty_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DateTimeProperty.MergeFrom(other.DateTimeProperty);
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.FooField != 0) {
        FooField = other.FooField;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            long? value = _single_nullableInt_codec.Read(input);
            if (nullableInt_ == null || value != 0L) {
              NullableInt = value;
            }
            break;
          }
          case 26: {
            if (dateTimeProperty_ == null) {
              dateTimeProperty_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(dateTimeProperty_);
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
          case 40: {
            fooField_ = (global::GrpcSample.Contracts.Services.HelleWorldResponse.Types.Foo) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the HelleWorldResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// SCREAMING_SNAKE_CASE used for enums.
      /// </summary>
      public enum Foo {
        /// <summary>
        ///// ERROR!!!
        /// </summary>
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("FIRST_VALUE")] FirstValue = 2,
        [pbr::OriginalName("SECOND_VALUE")] SecondValue = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
