// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_sample_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcSample.Contracts.Services {

  /// <summary>Holder for reflection information generated from grpc_sample_service.proto</summary>
  public static partial class GrpcSampleServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for grpc_sample_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GrpcSampleServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlncnBjX3NhbXBsZV9zZXJ2aWNlLnByb3RvEgpncnBjc2FtcGxlGiJncnBj",
            "X3NhbXBsZV9zZXJ2aWNlX21lc3NhZ2VzLnByb3RvGh5nb29nbGUvcHJvdG9i",
            "dWYvd3JhcHBlcnMucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAu",
            "cHJvdG8iIgoUR2V0SGVsbG9Xb3JsZFJlcXVlc3QSCgoCaWQYASABKAki4wEK",
            "EkhlbGxlV29ybGRSZXNwb25zZRIxCgxudWxsYWJsZV9pbnQYASABKAsyGy5n",
            "b29nbGUucHJvdG9idWYuSW50MzJWYWx1ZRI2ChJkYXRlX3RpbWVfcHJvcGVy",
            "dHkYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg8KB21lc3Nh",
            "Z2UYCCABKAkiNQoDQmFyEgsKB1VOS05PV04QABIPCgtGSVJTVF9WQUxVRRAB",
            "EhAKDFNFQ09ORF9WQUxVRRACSgQIAhADSgQIDxAQSgQICRAMUgNmb29SA2Jh",
            "cjKzAgoRR3JwY1NhbXBsZVNlcnZpY2USUwoNR2V0SGVsbG9Xb3JsZBIgLmdy",
            "cGNzYW1wbGUuR2V0SGVsbG9Xb3JsZFJlcXVlc3QaHi5ncnBjc2FtcGxlLkhl",
            "bGxlV29ybGRSZXNwb25zZSIAEj0KCEdldExpbmVzEhsuZ3JwY3NhbXBsZS5H",
            "ZXRMaW5lc1JlcXVlc3QaEC5ncnBjc2FtcGxlLkxpbmUiADABEj0KA1N1bRIZ",
            "LmdycGNzYW1wbGUuTnVtYmVyTWVzc2FnZRoXLmdycGNzYW1wbGUuU3VtUmVz",
            "cG9uc2UiACgBEksKCE11bHRpcGx5EhsuZ3JwY3NhbXBsZS5NdWx0aXBseVJl",
            "cXVlc3QaHC5ncnBjc2FtcGxlLk11bHRpcGx5UmVzcG9uc2UiACgBMAFCIKoC",
            "HUdycGNTYW1wbGUuQ29udHJhY3RzLlNlcnZpY2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GrpcSample.Contracts.Messages.GrpcSampleServiceMessagesReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcSample.Contracts.Services.GetHelloWorldRequest), global::GrpcSample.Contracts.Services.GetHelloWorldRequest.Parser, new[]{ "Id" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcSample.Contracts.Services.HelleWorldResponse), global::GrpcSample.Contracts.Services.HelleWorldResponse.Parser, new[]{ "NullableInt", "DateTimeProperty", "Message" }, null, new[]{ typeof(global::GrpcSample.Contracts.Services.HelleWorldResponse.Types.Bar) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetHelloWorldRequest : pb::IMessage<GetHelloWorldRequest> {
    private static readonly pb::MessageParser<GetHelloWorldRequest> _parser = new pb::MessageParser<GetHelloWorldRequest>(() => new GetHelloWorldRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetHelloWorldRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcSample.Contracts.Services.GrpcSampleServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHelloWorldRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHelloWorldRequest(GetHelloWorldRequest other) : this() {
      id_ = other.id_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHelloWorldRequest Clone() {
      return new GetHelloWorldRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetHelloWorldRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetHelloWorldRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetHelloWorldRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Hello World example message.
  ///
  ///CamelCase used for messages and rpc.
  /// </summary>
  public sealed partial class HelleWorldResponse : pb::IMessage<HelleWorldResponse> {
    private static readonly pb::MessageParser<HelleWorldResponse> _parser = new pb::MessageParser<HelleWorldResponse>(() => new HelleWorldResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HelleWorldResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcSample.Contracts.Services.GrpcSampleServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelleWorldResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelleWorldResponse(HelleWorldResponse other) : this() {
      NullableInt = other.NullableInt;
      DateTimeProperty = other.dateTimeProperty_ != null ? other.DateTimeProperty.Clone() : null;
      message_ = other.message_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HelleWorldResponse Clone() {
      return new HelleWorldResponse(this);
    }

    /// <summary>Field number for the "nullable_int" field.</summary>
    public const int NullableIntFieldNumber = 1;
    private static readonly pb::FieldCodec<int?> _single_nullableInt_codec = pb::FieldCodec.ForStructWrapper<int>(10);
    private int? nullableInt_;
    /// <summary>
    /// snake_case used form message properties.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int? NullableInt {
      get { return nullableInt_; }
      set {
        nullableInt_ = value;
      }
    }

    /// <summary>Field number for the "date_time_property" field.</summary>
    public const int DateTimePropertyFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dateTimeProperty_;
    /// <summary>
    /// xml comments will be autogenerated
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DateTimeProperty {
      get { return dateTimeProperty_; }
      set {
        dateTimeProperty_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 8;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HelleWorldResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HelleWorldResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NullableInt != other.NullableInt) return false;
      if (!object.Equals(DateTimeProperty, other.DateTimeProperty)) return false;
      if (Message != other.Message) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (nullableInt_ != null) hash ^= NullableInt.GetHashCode();
      if (dateTimeProperty_ != null) hash ^= DateTimeProperty.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (nullableInt_ != null) {
        _single_nullableInt_codec.WriteTagAndValue(output, NullableInt);
      }
      if (dateTimeProperty_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DateTimeProperty);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Message);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (nullableInt_ != null) {
        size += _single_nullableInt_codec.CalculateSizeWithTag(NullableInt);
      }
      if (dateTimeProperty_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DateTimeProperty);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HelleWorldResponse other) {
      if (other == null) {
        return;
      }
      if (other.nullableInt_ != null) {
        if (nullableInt_ == null || other.NullableInt != 0) {
          NullableInt = other.NullableInt;
        }
      }
      if (other.dateTimeProperty_ != null) {
        if (dateTimeProperty_ == null) {
          dateTimeProperty_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DateTimeProperty.MergeFrom(other.DateTimeProperty);
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            int? value = _single_nullableInt_codec.Read(input);
            if (nullableInt_ == null || value != 0) {
              NullableInt = value;
            }
            break;
          }
          case 26: {
            if (dateTimeProperty_ == null) {
              dateTimeProperty_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(dateTimeProperty_);
            break;
          }
          case 66: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the HelleWorldResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Bar {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("FIRST_VALUE")] FirstValue = 1,
        [pbr::OriginalName("SECOND_VALUE")] SecondValue = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
